### ISSUE TITLE
minimap & info table 

### ISSUE THREAD

**Issue by IdreesSamadi** [ItJustWorksTM/EiffelVis#19]
## Minimap

Enables users to view which section of the graph they are currently in. The utility of this feature scales with the size of the graph and the number of events. 
  
Goals:  

* Show where the user is in relation to the graph
* Allow user to navigate through the graph using the Minimap    
  
    
## Info Table

A small table on the top right corner of the graph to show which event is selected by the user. Currently, the table will show the id of the event, but more information can be added to it based on user preferences.

**Comment by IdreesSamadi** [comment]
used for better navigation

**Comment by RuthgerD** [comment]
What would this info table contain?

**Comment by IdreesSamadi** [comment]
to show more info about node 
![image](https://user-images.githubusercontent.com/57256007/134887174-b9834cc6-e587-4041-95ec-89be79f327fa.png)

**Comment by RuthgerD** [comment]
Won't the minimap stunt #17 a bit though? to render it youd need a larger data set than currently in view

**Comment by SyncInProgress** [comment]
It should be fine because the minimap only shows data which has been rendered. So it may be useless when the user is looking at a few nodes in the beginning. But once they choose to render more data, it can be confusing as to where they are on the graph. So the minimap will show which section on the graph they are currently viewing in relation to the rendered areas.
